const data = [{
    art_focus: "3",
    bars: null,
    city: "St. Louis",
    country: "USA",
    culture_focus: "3",
    description: "Some may just pass through on their way to the west, but come see why St. Louis is worth sticking around for!",
    difficulty_focus: "3",
    distance_from_user: "100000000000000000000000",
    distance_miles: "1.78",
    history_focus: "2",
    huntExtraLargePhotoURL: "https://photos.scavengerhunt.com/scavenger_hunt_locations/st_louis_scavenger_hunt_St._Louis_Missouri_team_building_1524242695_extra_large.jpg",
    huntLargePhotoURL: "https://photos.scavengerhunt.com/scavenger_hunt_locations/st_louis_scavenger_hunt_St._Louis_Missouri_team_building_1524242695_large.jpg",
    huntMediumPhotoURL: "https://photos.scavengerhunt.com/scavenger_hunt_locations/st_louis_scavenger_hunt_St._Louis_Missouri_team_building_1524242695_medium.jpg",
    huntPhotoURL: "https://photos.scavengerhunt.com/scavenger_hunt_locations/st_louis_scavenger_hunt_St._Louis_Missouri_team_building_1524242695_thumb.jpg",
    hunt_id: "1",
    hunt_type: "scavaHunt",
    key: "0",
    lat: "38.625535",
    long: "-90.188654",
    long_description: "      They call St. Louis “The Gateway to the West” but once you’ve experienced this amazing city you won’t ever want to leave. Parks and ballparks, magnificent courthouses and post office palaces, there's a lot to see on this epic scavenger hunt! You'll be helped along by Civil Rights heroes, a Disney favorite and a couple of Cardinals. It's time to strap on those walking shoes, round up some friends and book your St. Louis scavenger hunt today.",
    lr_long_description: "<p>Sky-high arches, epic art and baseball champions; we could only be talking about one city in Missouri. On this fun-filled St. Louis scavenger hunt, we make a loop around downtown in search of storied buildings, wondrous sculptures and great green spaces.</p><p>Who does the Gateway Arch remember? How did the Perfectos become the Cardinals? Find out on this scavenger hunt of St. Louis!</p>",
    name: "Gateway to the West",
    route_id: null,
    star_rating: "4.55",
    starting_location: "48 N 4th St, St Louis, MO 63102, USA",
    state: "Missouri",
    total_reviews: "126",
    url: "https://www.letsroam.com/scavenger_hunt/st_louis_scavenger_hunt.html"
  },
  {
    art_focus: "2",
    bars: null,
    city: "Chicago",
    country: "USA",
    culture_focus: "2",
    description: "You have never seen Chicago like this before! Race against the clock and get the highest score to win in the Windy City!",
    difficulty_focus: "1",
    distance_from_user: "100000000000000000000000",
    distance_miles: "2.41",
    history_focus: "2",
    huntExtraLargePhotoURL: "https://photos.scavengerhunt.com/scavenger_hunt_locations/Loop_Chicago_Scavenger_Hunt_Chicago_Illinois_team_building_1524242211_extra_large.jpg",
    huntLargePhotoURL: "https://photos.scavengerhunt.com/scavenger_hunt_locations/Loop_Chicago_Scavenger_Hunt_Chicago_Illinois_team_building_1524242211_large.jpg",
    huntMediumPhotoURL: "https://photos.scavengerhunt.com/scavenger_hunt_locations/Loop_Chicago_Scavenger_Hunt_Chicago_Illinois_team_building_1524242211_medium.jpg",
    huntPhotoURL: "https://photos.scavengerhunt.com/scavenger_hunt_locations/Loop_Chicago_Scavenger_Hunt_Chicago_Illinois_team_building_1524242211_thumb.jpg",
    hunt_id: "2",
    hunt_type: "scavaHunt",
    key: "1",
    lat: "41.88345043034215",
    long: "-87.62496390000001",
    long_description: `<p>          Named for the cable car turnarounds and the prominent   elevated railway that encircled the area at the end of the 19th century, the Loop is 
  ↵Chicago's commercial and cultural core. On todays epic scavenger hunt of Chicago, youll uncover the areas best sights and rich history. Along the way, youll visit Cloud Gate, Art Institute of
  ↵ Chicago, and the Federal Reserve Bank of 
  ↵Chicago. It's time to strap on those walking shoes, round up some friends and book your Chicago Loop scavenger hunt today!</p>`,
    lr_long_description: "<p>When navigating this commercial and cultural district, you may feel like you're going in circles. On this fun-filled Chicago Loop scavenger hunt, find all the storied buildings and epic sculptures south of the Chicago River.</p><p>Where will you find a cloud that never moves? Where does the city go to make million-dollar withdrawals? Find out on this scavenger hunt of Chicago!</p>",
    name: "Chicago Loop",
    route_id: "7",
    star_rating: "4.33",
    starting_location: "78 E Washington St, Chicago, IL 60602, USA",
    state: "Illinois",
    total_reviews: "599",
    url: "https://www.letsroam.com/scavenger_hunt/Loop_Chicago_Scavenger_Hunt.html"
  },
  {
    art_focus: "3",
    bars: null,
    city: "Denver",
    country: "USA",
    culture_focus: "2",
    description: "The gold may all be claimed in Colorado, but we'll show you there's still plenty of treasure in Denver's city center!",
    difficulty_focus: "3",
    distance_from_user: "100000000000000000000000",
    distance_miles: "2.01",
    history_focus: "3",
    huntExtraLargePhotoURL: "https://photos.scavengerhunt.com/scavenger_hunt_locations/denver_scavenger_hunt_Denver_Colorado_team_building_1524243135_extra_large.jpg",
    huntLargePhotoURL: "https://photos.scavengerhunt.com/scavenger_hunt_locations/denver_scavenger_hunt_Denver_Colorado_team_building_1524243135_large.jpg",
    huntMediumPhotoURL: "https://photos.scavengerhunt.com/scavenger_hunt_locations/denver_scavenger_hunt_Denver_Colorado_team_building_1524243135_medium.jpg",
    huntPhotoURL: "https://photos.scavengerhunt.com/scavenger_hunt_locations/denver_scavenger_hunt_Denver_Colorado_team_building_1524243135_thumb.jpg",
    hunt_id: "3",
    hunt_type: "scavaHunt",
    key: "2",
    lat: "39.739114",
    long: "-104.983951",
    long_description: "<p>A gold rush’s riches transformed the Colorado's state capital into one of the most beautiful cities in America. On today's epic scavenger hunt of Denver, you’ll make a loop around the city center in search of storied buildings, public art and tranquil parks. Along the way you’ll seek Justice at the State Capitol, find Beatles at the Performing Arts Complex and spot blue bears at the Convention Center. It’s time to strap on those walking shoes, round up some friends and book your Denver scavenger hunt today!<br></p>",
    lr_long_description: "<p>The Colorado Gold Rush produced one of the most stunning capital cities in the USA. On this fun-filled Denver scavenger hunt, you'll find downtown's historic buildings, epic sculptures and grand green spaces.</p><p>Will a Coloradoan ever reach the White House? Where do 40-foot blue bears like to chill? Find out on this scavenger hunt of Denver!</p>",
    name: "Denver's Golden Treasures",
    route_id: "11",
    star_rating: "4.44",
    starting_location: "1441 Grant St, Denver, CO 80203, USA",
    state: "Colorado",
    total_reviews: "79",
    url: "https://www.letsroam.com/scavenger_hunt/denver_scavenger_hunt.html"
  }
]

export default data;